version: '3.7'
services: 
  db:
    build:
      context: .
      dockerfile: dockerDb/Dockerfile
    image: 'mysql'
    restart: always
    ports: 
    - "3310:3306"
    environment:
      MYSQL_DATABASE: 'jalurbelanda'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
    - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: dockerApp/Dockerfile
    image: 'jalurbelanda'
    ports:
    - 8888:80
    volumes:
    - ./:/var/www/html